models:
  device: cpu
  clip: ViT-B/32
  stylegan: static/SG3.pkl
  wstds: static/W_STDS.pth
  ssat: static/SSAT.pth
  faceparsing: static/PARSING.pth

firebase:
  key-path: .firebase-pk.json
  storage-bucket: make-me-up-3cb4f.appspot.com
  users-bucket: make-me-up-3cb4f.appspot.com/users




